# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('custid', models.IntegerField(primary_key=True, serialize=False)),
                ('streetone', models.CharField(max_length=50)),
                ('streettwo', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('cookieid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('peanuts', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.IntegerField(primary_key=True, serialize=False)),
                ('cookamt', models.IntegerField()),
                ('price', models.FloatField()),
                ('cookieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookiez.Cookie')),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookiez.Customer')),
            ],
        ),
    ]
