# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiez', '0002_auto_20170503_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='description',
            field=models.CharField(default="it'z a cookie boiiiii", max_length=100),
            preserve_default=False,
        ),
    ]
