# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiez', '0004_cookie_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='imagePath',
            field=models.ImageField(default='/static/images/chocolate_chip_cooke.JPG', upload_to=b''),
        ),
    ]
