# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookiez', '0006_auto_20170503_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cookieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookiez.Cookie')),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookiez.Customer')),
            ],
        ),
    ]
